apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config-admin
data:
  SERVER_PORT: "{{ .Values.Properties.Admin.SERVER_PORT }}" #string
  {{- if .Values.Ingress.enabled }}
  SERVER_SERVLET_CONTEXTPATH: {{ .Values.Ingress.AdminPath }}{{ .Values.Properties.Admin.SERVER_SERVLET_CONTEXTPATH }}
  {{- else }}
  SERVER_SERVLET_CONTEXTPATH: {{ .Values.Properties.Admin.SERVER_SERVLET_CONTEXTPATH }}
  {{- end }}
  CUSTOM_SERVLET_SESSION_TIMEOUT: {{ .Values.Properties.Admin.CUSTOM_SERVLET_SESSION_TIMEOUT }}
  SERVER_SERVLET_SESSION_COOKIE_NAME: {{ .Values.Properties.Admin.SERVER_SERVLET_SESSION_COOKIE_NAME }}
  APPLICATION_TITLE: {{ .Values.Properties.Admin.APPLICATION_TITLE }}
  EVENT_RESERVED1: {{ .Values.Properties.Admin.EVENT_RESERVED1 }}
  EVENT_RESERVED2: {{ .Values.Properties.Admin.EVENT_RESERVED2 }}
  EVENT_RESERVED3: {{ .Values.Properties.Admin.EVENT_RESERVED3 }}
  EVENT_RESERVED4: {{ .Values.Properties.Admin.EVENT_RESERVED4 }}
  EVENT_RESERVED5: {{ .Values.Properties.Admin.EVENT_RESERVED5 }}
  USING_HELM_CONFIG: "{{ .Values.Properties.Admin.USING_HELM_CONFIG }}"
  BUILD_VERSION: !!stringEnv {{ quote .Values.Dep.Admin.image.tag }}
  SPRINGDOC_SWAGGERUI_PATH: {{ .Values.Properties.Admin.SPRINGDOC_SWAGGERUI_PATH }}
  SPRINGDOC_PATHSTOMATCH: {{ .Values.Properties.Admin.SPRINGDOC_PATHSTOMATCH }}
  LOGGING_CONFIG: {{ .Values.Properties.Admin.LOGGING_CONFIG }}
  SPRING_THYMELEAF_ENCODING: {{ .Values.Properties.Admin.SPRING_THYMELEAF_ENCODING }}
  SPRING_THYMELEAF_CACHE: "{{ .Values.Properties.Admin.SPRING_THYMELEAF_CACHE }}"
  SPRING_MESSAGES_BASENAME: {{ .Values.Properties.Admin.SPRING_MESSAGES_BASENAME }}
  SPRING_MESSAGES_CACHEDURATION: "{{ .Values.Properties.Admin.SPRING_MESSAGES_CACHEDURATION }}" #string
  SPRING_MESSAGES_ENCODING: {{ .Values.Properties.Admin.SPRING_MESSAGES_ENCODING }}
  SPRING_RESOURCES_CACHE_PERIOD: "{{ .Values.Properties.Admin.SPRING_RESOURCES_CACHE_PERIOD }}" #string
  SERVER_ERROR_WHITELABEL_ENABLED: "{{ .Values.Properties.Admin.SERVER_ERROR_WHITELABEL_ENABLED }}" #string
  DATATABLE_ERROR_MODE: {{ .Values.Properties.Admin.DATATABLE_ERROR_MODE }}
  DATATABLE_PAGE_LENGTH: "{{ .Values.Properties.Admin.DATATABLE_PAGE_LENGTH }}" #string
  SETTINGS_UPDATE_INITIAL_DELAY: "{{ .Values.Properties.Admin.SETTINGS_UPDATE_INITIAL_DELAY }}" #string
  SETTINGS_UPDATE_INTERVAL: "{{ .Values.Properties.Admin.SETTINGS_UPDATE_INTERVAL }}" #string
  LOGGING_LEVEL_ORG_KEYCLOAK: {{ .Values.Properties.Admin.LOGGING_LEVEL_ORG_KEYCLOAK }}
  LOGGING_LEVEL_COM_IMST_EVENT_MAP: {{ .Values.Properties.Admin.LOGGING_LEVEL_COM_IMST_EVENT_MAP }}
  LOGGING_LEVEL_COM_ZAXXER_HIKARI_HIKARICONFIG: {{ .Values.Properties.Admin.LOGGING_LEVEL_COM_ZAXXER_HIKARI_HIKARICONFIG }}
  LOGGING_LEVEL_COM_ZAXXER_HIKARI_POOL: {{ .Values.Properties.Admin.LOGGING_LEVEL_COM_ZAXXER_HIKARI_POOL }}
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: {{ .Values.Properties.Admin.LOGGING_LEVEL_ORG_SPRINGFRAMEWORK }}
  LOGGING_LEVEL_ORG_HIBERNATE: {{ .Values.Properties.Admin.LOGGING_LEVEL_ORG_HIBERNATE }}
  LOGGING_LEVEL_COM_GITHUB: {{ .Values.Properties.Admin.LOGGING_LEVEL_COM_GITHUB }}
  LOGGING_LEVEL_ORG_THYMELEAF: {{ .Values.Properties.Admin.LOGGING_LEVEL_ORG_THYMELEAF }}
  LOGGING_LEVEL_ORG_APACHE_HTTP: {{ .Values.Properties.Admin.LOGGING_LEVEL_ORG_APACHE_HTTP }}
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT_CONTEXT_WEB_ERRORPAGEFILTER: "{{ .Values.Properties.Admin.LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT_CONTEXT_WEB_ERRORPAGEFILTER }}" #string
  SPRING_DATASOURCE_HIKARI_CONNECTIONTIMEOUT: "{{ .Values.Properties.Admin.SPRING_DATASOURCE_HIKARI_CONNECTIONTIMEOUT }}" #string
  SPRING_SERVLET_MULTIPART_MAXFILESIZE: {{ .Values.Properties.Admin.SPRING_SERVLET_MULTIPART_MAXFILESIZE }}
  SPRING_SERVLET_MULTIPART_MAXREQUESTSIZE: {{ .Values.Properties.Admin.SPRING_SERVLET_MULTIPART_MAXREQUESTSIZE }}
  LDAP_CONTEXT_SOURCE_URL: {{ .Values.Properties.Admin.LDAP_CONTEXT_SOURCE_URL }}
  LDAP_CONTEXT_SOURCE_BASE: {{ .Values.Properties.Admin.LDAP_CONTEXT_SOURCE_BASE }}
  LDAP_CONTEXT_USER_DN: {{ .Values.Properties.Admin.LDAP_CONTEXT_USER_DN }}
  LDAP_CONTEXT_PASSWORD: {{ .Values.Properties.Admin.LDAP_CONTEXT_PASSWORD }}
  LDAP_USER_SEARCH_BASE: {{ .Values.Properties.Admin.LDAP_USER_SEARCH_BASE }}
  LDAP_USER_SEARCH_FILTER: {{ .Values.Properties.Admin.LDAP_USER_SEARCH_FILTER }}
  LDAP_USER_SEARCH_SEARCH_SUBTREE: "{{ .Values.Properties.Admin.LDAP_USER_SEARCH_SEARCH_SUBTREE }}" #string
  LDAP_USER_SEARCH_RESULT_EXCEPTION: "{{ .Values.Properties.Admin.LDAP_USER_SEARCH_RESULT_EXCEPTION }}" #string
  JAVAX_NET_SSL_TRUSTSTORE: {{ .Values.Properties.Admin.JAVAX_NET_SSL_TRUSTSTORE }}
  JAVAX_NET_SSL_TRUSTSTOREPASSWORD: {{ .Values.Properties.Admin.JAVAX_NET_SSL_TRUSTSTOREPASSWORD }}
  SAML_IDP_SERVER_NAME: {{ .Values.Properties.Admin.SAML_IDP_SERVER_NAME }}
  SAML_SP_SERVER_NAME: {{ .Values.Properties.Admin.SAML_SP_SERVER_NAME }}
  SAML_KEYSTORE_LOCATION: {{ .Values.Properties.Admin.SAML_KEYSTORE_LOCATION }}
  SAML_KEYSTORE_PASSWORD: {{ .Values.Properties.Admin.SAML_KEYSTORE_PASSWORD }}
  SAML_KEYSTORE_ALIAS: {{ .Values.Properties.Admin.SAML_KEYSTORE_ALIAS }}
  SAML_KEYSTORE_PRIVATEKEY_PASSWORD: {{ .Values.Properties.Admin.SAML_KEYSTORE_PRIVATEKEY_PASSWORD }}
  SAML_KEYSTORE_ENCRYPTION_METHOD: {{ .Values.Properties.Admin.SAML_KEYSTORE_ENCRYPTION_METHOD }}
  MASTER_DATASOURCE_JDBCURL: {{ .Values.Properties.Admin.MASTER_DATASOURCE_JDBCURL }}
  MASTER_DATASOURCE_USERNAME: {{ .Values.Properties.Admin.MASTER_DATASOURCE_USERNAME }}      
  MASTER_DATASOURCE_PASSWORD: {{ .Values.Properties.Admin.MASTER_DATASOURCE_PASSWORD }}
  JASYPT_ENCRYPTOR_ALGORITHM: {{ .Values.Properties.Admin.JASYPT_ENCRYPTOR_ALGORITHM }}
  JASYPT_ENCRYPTOR_PASSWORD: {{ .Values.Properties.Admin.JASYPT_ENCRYPTOR_PASSWORD }}
  JASYPT_ENCRYPTOR_IVGENERATORCLASSNAME: {{ .Values.Properties.Admin.JASYPT_ENCRYPTOR_IVGENERATORCLASSNAME }}
  MASTER_DATASOURCE_DRIVERCLASSNAME: {{ .Values.Properties.Admin.MASTER_DATASOURCE_DRIVERCLASSNAME }}
  MASTER_DATASOURCE_MAXIMUMPOOLSIZE: "{{ .Values.Properties.Admin.MASTER_DATASOURCE_MAXIMUMPOOLSIZE }}" #string
  MASTER_DATASOURCE_MINIMUMIDLE: "{{ .Values.Properties.Admin.MASTER_DATASOURCE_MINIMUMIDLE }}" #string
  MASTER_DATASOURCE_JPA_SHOWSQL: "{{ .Values.Properties.Admin.MASTER_DATASOURCE_JPA_SHOWSQL }}" #string
  SPRING_MAIN_ALLOWBEANDEFINITIONOVERRIDING: "{{ .Values.Properties.Admin.SPRING_MAIN_ALLOWBEANDEFINITIONOVERRIDING }}" #string
  SERVER_SSL_ENABLED: "{{ .Values.Properties.Admin.SERVER_SSL_ENABLED }}" #string
  SERVER_SSL_KEYSTORETYPE: {{ .Values.Properties.Admin.SERVER_SSL_KEYSTORETYPE }}
  SERVER_SSL_KEYSTORE: {{ .Values.Properties.Admin.SERVER_SSL_KEYSTORE }}
  SERVER_SSL_KEYSTOREPASSWORD: {{ .Values.Properties.Admin.SERVER_SSL_KEYSTOREPASSWORD }}
  S3SERVICEURL: {{ .Values.Properties.Admin.S3SERVICEURL }}
  S3ACCESSKEY: {{ .Values.Properties.Admin.S3ACCESSKEY }}
  S3SECRETKEY: {{ .Values.Properties.Admin.S3SECRETKEY }}
  S3BUCKETNAME: {{ .Values.Properties.Admin.S3BUCKETNAME }}
  S3REGION: {{ .Values.Properties.Admin.S3REGION }}
  KEYCLOAK_AUTHSERVERURL: {{ .Values.Properties.Admin.KEYCLOAK_AUTHSERVERURL }}
  KEYCLOAK_REALM: {{ .Values.Properties.Admin.KEYCLOAK_REALM }}
  KEYCLOAK_RESOURCE: {{ .Values.Properties.Admin.KEYCLOAK_RESOURCE }}
  KEYCLOAK_PUBLICCLIENT: "{{ .Values.Properties.Admin.KEYCLOAK_PUBLICCLIENT }}" #bool
  #KEYCLOAK_USE_RESOURCE_ROLE_MAPPINGS: "{{ .Values.Properties.Admin.KEYCLOAK_USE_RESOURCE_ROLE_MAPPINGS }}" #bool
  KEYCLOAK_CREDENTIALS_SECRET: {{ .Values.Properties.Admin.KEYCLOAK_CREDENTIALS_SECRET }}
  SPRING_JPA_HIBERNATE_DDLAUTO: {{ .Values.Properties.Admin.SPRING_JPA_HIBERNATE_DDLAUTO }}
  PGRESTORE_LOCATION: {{ .Values.Properties.Admin.PGRESTORE_LOCATION }}
  PGDUMP_LOCATION: {{ .Values.Properties.Admin.PGDUMP_LOCATION }}
  S3DUMPSPATH: {{ .Values.Properties.Admin.S3DUMPSPATH }}
  SPRING_REDIS_HOST: {{ .Values.Properties.Admin.SPRING_REDIS_HOST }}
  SPRING_REDIS_PORT: "{{ .Values.Properties.Admin.SPRING_REDIS_PORT }}"
  SPRING_REDIS_PASSWORD: {{ .Values.Properties.Admin.SPRING_REDIS_PASSWORD }}
  SPRING_SESSION_STORETYPE: {{ .Values.Properties.Admin.SPRING_SESSION_STORETYPE }}
  SPRING_SESSION_REDIS_FLUSH_MODE: {{ .Values.Properties.Admin.SPRING_SESSION_REDIS_FLUSH_MODE }}
  SPRING_SESSION_REDIS_NAMESPACE: {{ .Values.Properties.Admin.SPRING_SESSION_REDIS_NAMESPACE }}
  SPRING_SESSION_REDIS_WEB_NAMESPACE: {{ .Values.Properties.Admin.SPRING_SESSION_REDIS_WEB_NAMESPACE }}
  LOGGING_LEVEL_IO_LETTUCE: {{ .Values.Properties.Admin.LOGGING_LEVEL_IO_LETTUCE }}
  LOGGING_LEVEL_COM_ULISESBOCCHIO_JASYPTSPRINGBOOT: {{ .Values.Properties.Admin.LOGGING_LEVEL_COM_ULISESBOCCHIO_JASYPTSPRINGBOOT }}
  SRPING_JPA_PROPERTIES_HIBERNATE_GLOBALLYQUOTEDIDENTIFIERS: "{{ .Values.Properties.Admin.SRPING_JPA_PROPERTIES_HIBERNATE_GLOBALLYQUOTEDIDENTIFIERS }}"
  SRPING_DATASOURCE_INITIALIZATIONMODE: {{ .Values.Properties.Admin.SRPING_DATASOURCE_INITIALIZATIONMODE }}
  SRPING_DATASOURCE_DATA: {{ .Values.Properties.Admin.SRPING_DATASOURCE_DATA }}
  SRPING_DATASOURCE_CONTINUEONERROR: "{{ .Values.Properties.Admin.SRPING_DATASOURCE_CONTINUEONERROR }}"